spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=VALUE
    #url: jdbc:h2:mem:testdb
#СУБД
  h2:
    console:
      enabled: true

#Штука чтобы запускать скрипты
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

#штука для созжания таблиц в бд с помощью аннотаций
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true



#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#
#h2:
#  console:
#    enabled: true
#
#jpa:
#  #Автоэнервация схемы hibernate
#  #generate-ddL: false
#  generate-ddL: true
#
#  hibernate:
#    #ddl-auto: none
#    ddl-auto: create-drop
#
## Показываем запросы
#show-sql: true