spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    show-sql: true



#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#
#h2:
#  console:
#    enabled: true
#
#jpa:
#  #Автоэнервация схемы hibernate
#  #generate-ddL: false
#  generate-ddL: true
#
#  hibernate:
#    #ddl-auto: none
#    ddl-auto: create-drop
#
## Показываем запросы
#show-sql: true